// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuHoSPzOteJ4-xiQPDeMvRY3kBdBYJNBY',
    appId: '1:113118268412:web:6b634739c60452285f4079',
    messagingSenderId: '113118268412',
    projectId: 'learn-firebase-a278f',
    authDomain: 'learn-firebase-a278f.firebaseapp.com',
    storageBucket: 'learn-firebase-a278f.firebasestorage.app',
    measurementId: 'G-B6MC7KL863',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfg49YoUZToGBVVjSHvfrYWpj_iHVkbuw',
    appId: '1:113118268412:android:53b25fc322155d185f4079',
    messagingSenderId: '113118268412',
    projectId: 'learn-firebase-a278f',
    storageBucket: 'learn-firebase-a278f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvVJHMbd6WRZOsafqwFdfERIMWLlzqLiI',
    appId: '1:113118268412:ios:20baabd6ac467d815f4079',
    messagingSenderId: '113118268412',
    projectId: 'learn-firebase-a278f',
    storageBucket: 'learn-firebase-a278f.firebasestorage.app',
    iosBundleId: 'com.example.cashEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvVJHMbd6WRZOsafqwFdfERIMWLlzqLiI',
    appId: '1:113118268412:ios:20baabd6ac467d815f4079',
    messagingSenderId: '113118268412',
    projectId: 'learn-firebase-a278f',
    storageBucket: 'learn-firebase-a278f.firebasestorage.app',
    iosBundleId: 'com.example.cashEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuHoSPzOteJ4-xiQPDeMvRY3kBdBYJNBY',
    appId: '1:113118268412:web:756740d7df3385305f4079',
    messagingSenderId: '113118268412',
    projectId: 'learn-firebase-a278f',
    authDomain: 'learn-firebase-a278f.firebaseapp.com',
    storageBucket: 'learn-firebase-a278f.firebasestorage.app',
    measurementId: 'G-D637RP2049',
  );
}
